using System;
using System.Collections;
using System.Collections.Generic;
using TMPro;
using UnityEngine;
using Random = UnityEngine.Random;

public class RandomName : MonoBehaviour
{
    private TMP_InputField _inputField;
    private readonly List<string> _randomNames = new List<string>()
    {
        "Abuzz Heartbreaker",
        "Alphabetic Afterimage",
        "Anony Mouse",
        "Arabic Denial",
        "Ass Ass In",
        "Ass Whupper",
        "Ayam Taken",
        "Bad Karma",
        "BeenThere DoneThat",
        "Behind You",
        "Ben Dover",
        "Berb DiWire",
        "Blurry Image",
        "Born Confused",
        "Bros Before Hoes",
        "Butt Smasher",
        "Casanova",
        "Cementitious Day",
        "Cereal Killer",
        "Counterclockwise Chi",
        "Cover Boy",
        "Cuddly Goblin",
        "Depressing Mistake",
        "Dildo Swaggins",
        "Dumbest Man Alive",
        "Endogamous Gnetum",
        "Epic Fail",
        "Erectile Reptile",
        "Google MeNow",
        "Grammar Jew",
        "Hakuna Matata",
        "HeirToThe PubicRegion",
        "HerpesFree Since03",
        "Hershey Squirts",
        "Hey You",
        "HeyYou NotYouYou",
        "Hitlersaurus Christ",
        "How You Doing",
        "Hugs for Drugs",
        "ImaComplete CyclePath",
        "Image Not Uploaded",
        "InJail OutSoon",
        "Intelligent Zombie",
        "Intradouching Myshelf",
        "Itchy And Scratchy",
        "James Blonde",
        "JeanClaude VanDarnItAll",
        "Jesus HentaiChrist",
        "Juilius Sneezer",
        "Justin Case",
        "KingOf Diary Queen",
        "Kiss My Axe",
        "Laugh TillYouPee",
        "Liu Kang Baking A Pie",
        "Magic Fetus",
        "Malice Aforethought",
        "Mechanic Mike",
        "My Name Is",
        "MyName IsInUse",
        "MyName Rocks",
        "Name NotImportant",
        "Nameless Faceless",
        "No Child Support",
        "Nonrecreational Filth",
        "Noway Out",
        "Once UponADime",
        "Oprah Windfury",
        "Period Blood",
        "Photo Coming Soon",
        "Pluralizes Everythings",
        "aDistraction",
        "Postmenopausal Spree",
        "Prince Charming",
        "Random Advice",
        "Real Name Hidden",
        "Russian Spy",
        "Say My Name",
        "Shaquille Oatmeal",
        "Sloppy Mcfloppy",
        "Sloppy Wet",
        "SwipeRight ForMe",
        "Tea Baggins",
        "Test Name",
        "That’s Me",
        "The Rapist",
        "This AintMe",
        "Uncommon Name",
        "Uncompartmented Bob",
        "Unfinished Sentenc",
        "Unmodified Workman",
        "Unobjectionable Pawn",
        "WellEndowed Penguin",
        "Whatcha LookingAt",
        "Who Am I?",
        "Willy Wanka",
        "WreckTangle",
        "Wretched Me",
        "XBOX Signout",
        "You Suck",
        "Zero Chills",
        "Queef Latina",
        "fast and the curious",
        "Shaquille UNIEL",
        "The Entire Population of Texas",
        "OwenWilsonsNose",
        "BadKarma",
        "Google Was My Idea",
        "Fedora the explorer",
        "YellowSnowman",
        "AllGoodNamesRGone",
        "thegodfatherpart4",
        "kentuckycriedfricken",
        "bigfootisreal",
        "fatBatman",
        "PaniniHead",
        "Bread Pitt",
        "Ariana Grandes Ponytail",
        "Bud Lightyear",
        "crazy cat lady",
        "Tin foil hat"
    };

    public void Awake()
    {
        _inputField = GetComponent<TMP_InputField>();
    }

    public void RandomNameInsert()
    {
        int indexRandomName = Random.Range(0, _randomNames.Count - 1);
        _inputField.text = _randomNames[indexRandomName];
    }
}
